name = "SpatialBoundaries"
uuid = "8d2ba62a-3d23-4a2b-b692-6b63e9267be2"
authors = ["Tanya Strydom <tanya.strydom@umontreal.ca>", "Timoth√©e Poisot <timothee.poisot@umontreal.ca>"]
version = "0.0.1"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Delaunay = "07eb4e4e-0c6d-46ef-bc4e-83d5e5d860a9"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NeutralLandscapes = "71847384-8354-4223-ac08-659a5128069f"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
SimpleSDMLayers = "2c645270-77db-11e9-22c3-0f302a89c64c"
SpatialEcology = "348f2d5d-71a3-5ad4-b565-8af070f99681"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"

[compat]
Plots = "1.16"
julia = "1.6"
