[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
GBIF = "ee291a33-5a6c-5552-a3c8-0f29a1181037"
GLM = "38e38edf-8417-5370-95a0-9cbb8c7f171a"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
NeutralLandscapes = "71847384-8354-4223-ac08-659a5128069f"
SimpleSDMLayers = "2c645270-77db-11e9-22c3-0f302a89c64c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
